-- Drop dependent objects first to ensure a clean slate
DROP TRIGGER IF EXISTS on_new_comment_created ON public.comments;
DROP FUNCTION IF EXISTS public.handle_new_reply_notification();
DROP TABLE IF EXISTS public.notifications;

-- Create notifications table
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL, -- The user to notify
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE, -- The user who triggered the notification
  comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE, -- The new comment/reply
  problem_id UUID, -- Link to the problem for context
  type TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- RLS: Users can only see and manage their own notifications
CREATE POLICY "Users can view and manage their own notifications"
ON public.notifications
FOR ALL
TO authenticated
USING (auth.uid() = user_id);

-- Function to create a notification when a reply is posted
CREATE OR REPLACE FUNCTION public.handle_new_reply_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  parent_comment_author_id UUID;
  parent_comment_problem_id UUID;
  parent_comment_solution_id UUID;
  problem_context_id UUID;
BEGIN
  -- Only trigger for replies (i.e., when parent_id is not null)
  IF NEW.parent_id IS NOT NULL THEN
    -- Find the author and context of the parent comment
    SELECT
      user_id,
      problem_id,
      solution_id
    INTO
      parent_comment_author_id,
      parent_comment_problem_id,
      parent_comment_solution_id
    FROM public.comments
    WHERE id = NEW.parent_id;

    -- Ensure we don't notify a user if they reply to their own comment
    IF parent_comment_author_id IS NOT NULL AND parent_comment_author_id != NEW.user_id THEN
      -- Determine the problem_id for context
      IF parent_comment_problem_id IS NOT NULL THEN
        problem_context_id := parent_comment_problem_id;
      ELSE
        SELECT problem_id INTO problem_context_id FROM public.solutions WHERE id = parent_comment_solution_id;
      END IF;

      -- Insert the notification
      INSERT INTO public.notifications (user_id, sender_id, comment_id, problem_id, type)
      VALUES (
        parent_comment_author_id,
        NEW.user_id,
        NEW.id,
        problem_context_id,
        'new_reply'
      );
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

-- Trigger to call the function after a new comment is inserted
CREATE TRIGGER on_new_comment_created
  AFTER INSERT ON public.comments
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_reply_notification();