-- Drop the comments table if it exists to apply new schema
DROP TABLE IF EXISTS public.comments CASCADE;

-- Create the comments table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  problem_id UUID REFERENCES public.problems(id) ON DELETE CASCADE,
  solution_id UUID REFERENCES public.solutions(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (length(content) > 0),
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  -- Ensure a comment is linked to either a problem or a solution, but not both or neither.
  CONSTRAINT chk_comment_parent
    CHECK (
      (problem_id IS NOT NULL AND solution_id IS NULL) OR
      (problem_id IS NULL AND solution_id IS NOT NULL)
    )
);

-- Add indexes for performance, checking if they exist first
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON public.comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_problem_id ON public.comments(problem_id);
CREATE INDEX IF NOT EXISTS idx_comments_solution_id ON public.comments(solution_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON public.comments(parent_id);

-- Enable RLS (this is idempotent, so it's safe to run again)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Drop the trigger if it exists, then re-create it to ensure it's up to date
DROP TRIGGER IF EXISTS update_comments_updated_at ON public.comments;
CREATE TRIGGER update_comments_updated_at
  BEFORE UPDATE ON public.comments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
